[package]
name = "contextual-identities"
version = "0.1.0"
authors = ["Roman Volosatovs <rvolosatovs@riseup.net>"]
edition = "2018"
description = "This crate provides wrappers around contextualIdentities Web API"
repository = "https://github.com/rvolosatovs/contextual-identities"
license = "MIT OR Apache-2.0"
keywords = ["api", "serde", "wasm", "web", "webassembly"]
categories = ["api-bindings", "wasm"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
contextual-identities-sys = "0.1.1"
js-sys = "0.3.44"
serde = { version = "1.0.115", features = ["derive"] }
serde_derive = "1.0.115"
wasm-bindgen = { version = "0.2.67", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4.17"
serde_json = "1.0.57"

[dev-dependencies]
wasm-bindgen-test = "0.3.13"
